modLoader="javafml"
loaderVersion="[${loader_version},)"
issueTrackerURL="https://github.com/mekanism/Mekanism/issues"

[[mods]]
    modId="mekanismtools"
    version="${version}"
    displayName="Mekanism: Tools"
    displayURL="http://aidancbrady.com/mekanism/"
    authors="Aidancbrady, Thommy101, Thiakil, pupnewfster, dizzyd"
    credits="unpairedbracket, CyanideX and many others"
    description='''Tools module for Mekanism'''

[[dependencies.mekanismtools]]
    modId="mekanism"
    mandatory=true
    versionRange="[${version}]"
    side="BOTH"