package mekanism.generators.common;

public enum GeneratorsBlock {
    HEAT_GENERATOR,
    SOLAR_GENERATOR,
    GAS_BURNING_GENERATOR,
    BIO_GENERATOR,
    ADVANCED_SOLAR_GENERATOR,
    WIND_GENERATOR,
    TURBINE_ROTOR,
    ROTATIONAL_COMPLEX,
    ELECTROMAGNETIC_COIL,
    TURBINE_CASING,
    TURBINE_VALVE,
    TURBINE_VENT,
    SATURATING_CONDENSER,
    REACTOR_CONTROLLER,
    REACTOR_FRAME,
    REACTOR_PORT,
    REACTOR_LOGIC_ADAPTER,
    REACTOR_GLASS,
    LASER_FOCUS_MATRIX;

    GeneratorsBlock() {

    }
}