project_identifier: mekanism
api_key_env: CROWDIN_API_KEY
commit_message: "[ci skip]"
base_path: .
files:
  - source: /src/datagen/generated/mekanism/assets/mekanism/lang/en_us.json
    translation: /src/main/resources/assets/mekanism/lang/%locale_with_underscore%.json
    languages_mapping:
      locale_with_underscore:
        af: af_za
        ar: ar_sa
        ast: ast_es
        az: az_az
        ba: ba_ru
        be: be_by
        bg: bg_bg
        br-FR: br_fr
        bs: bs_ba
        ca: ca_es
        cs: cs_cz
        cy: cy_gb
        da: da_dk
        de-AT: de_at
        de-CH: de_ch
        de: de_de
        el: el_gr
        en-AU: en_au
        en-CA: en_ca
        en-GB: en_gb
        en-NZ: en_nz
        en-PT: en_pt
        en-US: en_us
        en-ZA: en_za
        eo: eo_uy
        es-AR: es_ar
        es-CL: es_cl
        es-ES: es_es
        es-MX: es_mx
        es-UY: es_uy
        es-VE: es_ve
        et: et_ee
        eu: eu_es
        fa: fa_ir
        fi: fi_fi
        fil: fil_ph
        fo: fo_fo
        fr-CA: fr_ca
        fr: fr_fr
        fra-DE: fra_de
        fy-NL: fy_nl
        ga-IE: ga_ie
        gd: gd_gb
        gl: gl_es
        got: got_de
        gv: gv_im
        haw: haw_us
        he: he_il
        hi: hi_in
        hr: hr_hr
        hu: hu_hu
        hy-AM: hy_am
        id: id_id
        ig: ig_ng
        ido: io_en
        is: is_is
        it: it_it
        ja: ja_jp
        jbo: jbo_en
        ka: ka_ge
        kab: kab_kab
        kk: kk_kz
        kn: kn_in
        ko: ko_kr
        kw: kw_gb
        la-LA: la_va
        lb: lb_lu
        li: li_li
        lol: lol_us
        lt: lt_lt
        lv: lv_lv
        mi: mi_nz
        mk: mk_mk
        mn: mn_mn
        moh: moh_ca
        ms: ms_my
        mt: mt_mt
        nb: nb_no
        nds: nds_de
        nl-BE: nl_be
        nl: nl_nl
        nn-NO: nn_no
        #no: nn_no
        oc: oc_fr
        oj: oj_ca
        pl: pl_pl
        pt-BR: pt_br
        pt-PT: pt_pt
        qya-AA: qya_aa
        ro: ro_ro
        ru: ru_ru
        sk: sk_sk
        sl: sl_si
        so: so_so
        sq: sq_al
        sr: sr_sp
        sv-SE: sv_se
        ta: ta_in
        th: th_th
        tl: tl_ph
        tlh-AA: tlh_aa
        tr: tr_tr
        tt-RU: tt_ru
        tzl: tzl_tzl
        uk: uk_ua
        val-ES: val_es
        vec: vec_it
        vi: vi_vn
        yi: yi_de
        yo: yo_ng
        zh-CN: zh_cn
        zh-TW: zh_tw
  - source: >-
      /src/datagen/generated/mekanismadditions/assets/mekanismadditions/lang/en_us.json
    translation: >-
      /src/additions/resources/assets/mekanismadditions/lang/%locale_with_underscore%.json
    languages_mapping:
      locale_with_underscore:
        af: af_za
        ar: ar_sa
        ast: ast_es
        az: az_az
        ba: ba_ru
        be: be_by
        bg: bg_bg
        br-FR: br_fr
        bs: bs_ba
        ca: ca_es
        cs: cs_cz
        cy: cy_gb
        da: da_dk
        de-AT: de_at
        de-CH: de_ch
        de: de_de
        el: el_gr
        en-AU: en_au
        en-CA: en_ca
        en-GB: en_gb
        en-NZ: en_nz
        en-PT: en_pt
        en-US: en_us
        en-ZA: en_za
        eo: eo_uy
        es-AR: es_ar
        es-CL: es_cl
        es-ES: es_es
        es-MX: es_mx
        es-UY: es_uy
        es-VE: es_ve
        et: et_ee
        eu: eu_es
        fa: fa_ir
        fi: fi_fi
        fil: fil_ph
        fo: fo_fo
        fr-CA: fr_ca
        fr: fr_fr
        fra-DE: fra_de
        fy-NL: fy_nl
        ga-IE: ga_ie
        gd: gd_gb
        gl: gl_es
        got: got_de
        gv: gv_im
        haw: haw_us
        he: he_il
        hi: hi_in
        hr: hr_hr
        hu: hu_hu
        hy-AM: hy_am
        id: id_id
        ig: ig_ng
        ido: io_en
        is: is_is
        it: it_it
        ja: ja_jp
        jbo: jbo_en
        ka: ka_ge
        kab: kab_kab
        kk: kk_kz
        kn: kn_in
        ko: ko_kr
        kw: kw_gb
        la-LA: la_va
        lb: lb_lu
        li: li_li
        lol: lol_us
        lt: lt_lt
        lv: lv_lv
        mi: mi_nz
        mk: mk_mk
        mn: mn_mn
        moh: moh_ca
        ms: ms_my
        mt: mt_mt
        nb: nb_no
        nds: nds_de
        nl-BE: nl_be
        nl: nl_nl
        nn-NO: nn_no
        #no: nn_no
        oc: oc_fr
        oj: oj_ca
        pl: pl_pl
        pt-BR: pt_br
        pt-PT: pt_pt
        qya-AA: qya_aa
        ro: ro_ro
        ru: ru_ru
        sk: sk_sk
        sl: sl_si
        so: so_so
        sq: sq_al
        sr: sr_sp
        sv-SE: sv_se
        ta: ta_in
        th: th_th
        tl: tl_ph
        tlh-AA: tlh_aa
        tr: tr_tr
        tt-RU: tt_ru
        tzl: tzl_tzl
        uk: uk_ua
        val-ES: val_es
        vec: vec_it
        vi: vi_vn
        yi: yi_de
        yo: yo_ng
        zh-CN: zh_cn
        zh-TW: zh_tw
  - source: >-
      /src/datagen/generated/mekanismgenerators/assets/mekanismgenerators/lang/en_us.json
    translation: >-
      /src/generators/resources/assets/mekanismgenerators/lang/%locale_with_underscore%.json
    languages_mapping:
      locale_with_underscore:
        af: af_za
        ar: ar_sa
        ast: ast_es
        az: az_az
        ba: ba_ru
        be: be_by
        bg: bg_bg
        br-FR: br_fr
        bs: bs_ba
        ca: ca_es
        cs: cs_cz
        cy: cy_gb
        da: da_dk
        de-AT: de_at
        de-CH: de_ch
        de: de_de
        el: el_gr
        en-AU: en_au
        en-CA: en_ca
        en-GB: en_gb
        en-NZ: en_nz
        en-PT: en_pt
        en-US: en_us
        en-ZA: en_za
        eo: eo_uy
        es-AR: es_ar
        es-CL: es_cl
        es-ES: es_es
        es-MX: es_mx
        es-UY: es_uy
        es-VE: es_ve
        et: et_ee
        eu: eu_es
        fa: fa_ir
        fi: fi_fi
        fil: fil_ph
        fo: fo_fo
        fr-CA: fr_ca
        fr: fr_fr
        fra-DE: fra_de
        fy-NL: fy_nl
        ga-IE: ga_ie
        gd: gd_gb
        gl: gl_es
        got: got_de
        gv: gv_im
        haw: haw_us
        he: he_il
        hi: hi_in
        hr: hr_hr
        hu: hu_hu
        hy-AM: hy_am
        id: id_id
        ig: ig_ng
        ido: io_en
        is: is_is
        it: it_it
        ja: ja_jp
        jbo: jbo_en
        ka: ka_ge
        kab: kab_kab
        kk: kk_kz
        kn: kn_in
        ko: ko_kr
        kw: kw_gb
        la-LA: la_va
        lb: lb_lu
        li: li_li
        lol: lol_us
        lt: lt_lt
        lv: lv_lv
        mi: mi_nz
        mk: mk_mk
        mn: mn_mn
        moh: moh_ca
        ms: ms_my
        mt: mt_mt
        nb: nb_no
        nds: nds_de
        nl-BE: nl_be
        nl: nl_nl
        nn-NO: nn_no
        #no: nn_no
        oc: oc_fr
        oj: oj_ca
        pl: pl_pl
        pt-BR: pt_br
        pt-PT: pt_pt
        qya-AA: qya_aa
        ro: ro_ro
        ru: ru_ru
        sk: sk_sk
        sl: sl_si
        so: so_so
        sq: sq_al
        sr: sr_sp
        sv-SE: sv_se
        ta: ta_in
        th: th_th
        tl: tl_ph
        tlh-AA: tlh_aa
        tr: tr_tr
        tt-RU: tt_ru
        tzl: tzl_tzl
        uk: uk_ua
        val-ES: val_es
        vec: vec_it
        vi: vi_vn
        yi: yi_de
        yo: yo_ng
        zh-CN: zh_cn
        zh-TW: zh_tw
  - source: /src/datagen/generated/mekanismtools/assets/mekanismtools/lang/en_us.json
    translation: >-
      /src/tools/resources/assets/mekanismtools/lang/%locale_with_underscore%.json
    languages_mapping:
      locale_with_underscore:
        af: af_za
        ar: ar_sa
        ast: ast_es
        az: az_az
        ba: ba_ru
        be: be_by
        bg: bg_bg
        br-FR: br_fr
        bs: bs_ba
        ca: ca_es
        cs: cs_cz
        cy: cy_gb
        da: da_dk
        de-AT: de_at
        de-CH: de_ch
        de: de_de
        el: el_gr
        en-AU: en_au
        en-CA: en_ca
        en-GB: en_gb
        en-NZ: en_nz
        en-PT: en_pt
        en-US: en_us
        en-ZA: en_za
        eo: eo_uy
        es-AR: es_ar
        es-CL: es_cl
        es-ES: es_es
        es-MX: es_mx
        es-UY: es_uy
        es-VE: es_ve
        et: et_ee
        eu: eu_es
        fa: fa_ir
        fi: fi_fi
        fil: fil_ph
        fo: fo_fo
        fr-CA: fr_ca
        fr: fr_fr
        fra-DE: fra_de
        fy-NL: fy_nl
        ga-IE: ga_ie
        gd: gd_gb
        gl: gl_es
        got: got_de
        gv: gv_im
        haw: haw_us
        he: he_il
        hi: hi_in
        hr: hr_hr
        hu: hu_hu
        hy-AM: hy_am
        id: id_id
        ig: ig_ng
        ido: io_en
        is: is_is
        it: it_it
        ja: ja_jp
        jbo: jbo_en
        ka: ka_ge
        kab: kab_kab
        kk: kk_kz
        kn: kn_in
        ko: ko_kr
        kw: kw_gb
        la-LA: la_va
        lb: lb_lu
        li: li_li
        lol: lol_us
        lt: lt_lt
        lv: lv_lv
        mi: mi_nz
        mk: mk_mk
        mn: mn_mn
        moh: moh_ca
        ms: ms_my
        mt: mt_mt
        nb: nb_no
        nds: nds_de
        nl-BE: nl_be
        nl: nl_nl
        nn-NO: nn_no
        #no: nn_no
        oc: oc_fr
        oj: oj_ca
        pl: pl_pl
        pt-BR: pt_br
        pt-PT: pt_pt
        qya-AA: qya_aa
        ro: ro_ro
        ru: ru_ru
        sk: sk_sk
        sl: sl_si
        so: so_so
        sq: sq_al
        sr: sr_sp
        sv-SE: sv_se
        ta: ta_in
        th: th_th
        tl: tl_ph
        tlh-AA: tlh_aa
        tr: tr_tr
        tt-RU: tt_ru
        tzl: tzl_tzl
        uk: uk_ua
        val-ES: val_es
        vec: vec_it
        vi: vi_vn
        yi: yi_de
        yo: yo_ng
        zh-CN: zh_cn
        zh-TW: zh_tw
