# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx4G
org.gradle.configuration-cache=true

java_version=25
minecraft_version=26.3
#Used as a helper for porting when deps we use have not updated yet
major_minecraft_version=26.3
previous_minecraft_version=1.21.1
previous_minor_minecraft_version=26.1.2
neo_version=26.3.0.4-beta
mod_version=10.8.0
#This determines the minimum version of forge required to use Mekanism
# Only bump it whenever we need access to a feature in forge that is not available in earlier versions
neo_version_range=[26.3.0.4-beta,)
minecraft_version_range=[26.3,26.4)
#This specifies what type of release it will be uploaded to CurseForge and Modrinth as
# options are: alpha, beta, release
release_type=alpha

#JUnit/Testing dependencies
junit_version=6.1.3
jqwik_version=1.10.1

#misc settings
# recipe viewer, currently accepts: jei, emi, hybrid, none
recipe_viewer=jei

#datagen
yamlops_version=1.3.0

#Mod dependencies
cc_tweaked_version=1.120.2
crafttweaker_version=21.0.38
ctm_version=1.21-1.2.1+3
curios_version=16.0.0+26.2
emi_version=1.1.24+1.21.1
framedblocks_id=8750384
gender_mod_id=8891490
jade_id=8892782
jade_api_id=5427895
#Maven (unofficial)
jade_version=mc26.1-NeoForge-26.0.10
jeitweaker_version=8.0.6
jei_version=31.0.0.5
projecte_api_id=6611986
recipe_stages_version=8.0.0.2
top_version=26.2_neo-15.0.1-2
wthit_version=20.0.0

#Mod dependency min version ranges
jei_version_range=[31.0.0.5,)

#Mod dependency min version ranges until next MC version. For deps that we need a min version of but otherwise don't have to force ourselves loading after


#Mod dependencies for recipes (only used by our data generators)
ae2_version=26.1.10-beta
biomesoplenty_version=26.2-26.2.0.0.24
biomeswevegone_id=8259992
corgilib_id=7386252
farmers_delight_id=8765184
geckolib_id=8893169
glitchcore_version=26.2-26.2.0.0.0
ohthetreesyoullgrow_id=8282526
projecte_id=6611984
terrablender_version=26.2-26.2.0.0.2
