# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.configuration-cache=true

java_version=21
minecraft_version=1.21.11
#Used as a helper for porting when deps we use have not updated yet
major_minecraft_version=1.21
previous_minecraft_version=1.21.1
previous_minor_minecraft_version=1.21.6
neo_version=21.11.17-beta
mod_version=10.7.15
#This determines the minimum version of forge required to use Mekanism
# Only bump it whenever we need access to a feature in forge that is not available in earlier versions
neo_version_range=[21.8.25,)
minecraft_version_range=[1.21.8]
#This specifies what type of release it will be uploaded to CurseForge and Modrinth as
# options are: alpha, beta, release
release_type=alpha

#JUnit/Testing dependencies
junit_version=5.14.1
jqwik_version=1.9.3

#Parchment Settings
neoForge.parchment.minecraftVersion=1.21.10
neoForge.parchment.mappingsVersion=2025.10.12

#misc settings
# recipe viewer, currently accepts: jei, emi, hybrid
recipe_viewer=jei

#datagen
yamlops_version=1.3.0

#Mod dependencies
jade_id=7313008
jei_version=27.3.0.14
wthit_version=18.0.4

#Mod dependency min version ranges
jei_version_range=[27.3.0.14,)

#Mod dependency min version ranges until next MC version. For deps that we need a min version of but otherwise don't have to force ourselves loading after


#Mod dependencies for recipes (only used by our data generators)
ae2_version=19.2.17
biomesoplenty_version=21.11.0.6
biomeswevegone_id=7386826
corgilib_id=7386252
geckolib_id=7384016
glitchcore_version=21.11.0.2
ohthetreesyoullgrow_id=7363818
terrablender_version=21.11.0.0

#Outdated mod dependencies
cc_tweaked_version=1.111.0
crafttweaker_version=21.0.27
ctm_version=1.2.1+3
curios_version=11.0.2-alpha.1+1.21.5
emi_version=1.1.22
flux_networks_id=6089446
framedblocks_mod_id=6872949
grand_power_version=3.0.2
#TODO - 1.21.11: Figure out if jade had any changes to the API and if so either ask them to make an API jar again or just compile against the main jar
jade_api_id=5427895
jeitweaker_version=8.0.6
json_things_version=0.17.0
oc2_id=3896581
projecte_api_id=6611986
top_version=1.21_neo-12.0.4-6
wildfire_gender_mod_id=5579007
recipe_stages_version=8.0.0.2

#Outdated mod dependencies for recipes
farmers_delight_id=6917256
projecte_id=6611984