# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.configuration-cache=true
java_version=25
minecraft_version=26.2
#Used as a helper for porting when deps we use have not updated yet
major_minecraft_version=26.2
previous_minecraft_version=1.21.1
previous_minor_minecraft_version=26.1.2
neo_version=26.2.0.62
mod_version=10.8.0
#This determines the minimum version of forge required to use Mekanism
# Only bump it whenever we need access to a feature in forge that is not available in earlier versions
neo_version_range=[26.2.0.60,)
minecraft_version_range=[26.2,26.3)
#This specifies what type of release it will be uploaded to CurseForge and Modrinth as
# options are: alpha, beta, release
release_type=alpha

#JUnit/Testing dependencies
junit_version=6.1.2
jqwik_version=1.10.1

#misc settings
# recipe viewer, currently accepts: jei, emi, hybrid, none
recipe_viewer=jei

#datagen
yamlops_version=1.3.0

#Mod dependencies
cc_tweaked_version=1.120.1
crafttweaker_version=21.0.38
ctm_version=1.21-1.2.1+3
curios_version=15.0.0-beta.2+26.1.2
emi_version=1.1.24+1.21.1
framedblocks_id=8371586
jade_id=8326243
jade_api_id=5427895
#Maven (unofficial)
jade_version=mc26.1-NeoForge-26.0.10
jeitweaker_version=8.0.6
jei_version=30.14.0.89
projecte_api_id=6611986
recipe_stages_version=8.0.0.2
top_version=1.21_neo-12.0.8-7
wildfire_gender_mod_id=5579007
wthit_version=19.0.1

#Mod dependency min version ranges
jei_version_range=[30.12.0.69,)

#Mod dependency min version ranges until next MC version. For deps that we need a min version of but otherwise don't have to force ourselves loading after


#Mod dependencies for recipes (only used by our data generators)
ae2_version=26.1.10-beta
biomesoplenty_version=26.2-26.1.2.0.45
biomeswevegone_id=8259992
corgilib_id=7386252
farmers_delight_id=8083481
geckolib_id=8327604
glitchcore_version=26.2-26.2.0.0.0
ohthetreesyoullgrow_id=8282526
projecte_id=6611984
terrablender_version=26.2-26.2.0.0.2
