
pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        gradlePluginPortal()
        mavenCentral()
    }
}

plugins {
    id('org.gradle.toolchains.foojay-resolver-convention') version('1.0.0')
}

include('annotation-processor')
