package mekanism.generators.common;

import java.util.concurrent.CompletableFuture;
import mekanism.common.BasePackMetadataGenerator;
import mekanism.common.MekanismDataGenerator;
import mekanism.generators.client.GeneratorsBlockStateProvider;
import mekanism.generators.client.GeneratorsItemModelProvider;
import mekanism.generators.client.GeneratorsLangProvider;
import mekanism.generators.client.GeneratorsSoundProvider;
import mekanism.generators.client.GeneratorsSpriteSourceProvider;
import mekanism.generators.common.loot.GeneratorsLootProvider;
import net.minecraft.core.HolderLookup;
import net.minecraft.data.DataGenerator;
import net.minecraft.data.DataProvider;
import net.minecraftforge.common.data.ExistingFileHelper;
import net.minecraftforge.data.event.GatherDataEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod.EventBusSubscriber;
import net.minecraftforge.fml.common.Mod.EventBusSubscriber.Bus;

@EventBusSubscriber(modid = MekanismGenerators.MODID, bus = Bus.MOD)
public class GeneratorsDataGenerator {

    private GeneratorsDataGenerator() {
    }

    @SubscribeEvent
    public static void gatherData(GatherDataEvent event) {
        MekanismDataGenerator.bootstrapConfigs(MekanismGenerators.MODID);
        DataGenerator gen = event.getGenerator();
        ExistingFileHelper existingFileHelper = event.getExistingFileHelper();
        CompletableFuture<HolderLookup.Provider> lookupProvider = event.getLookupProvider();
        addProvider(gen, true, output -> new BasePackMetadataGenerator(output, GeneratorsLang.PACK_DESCRIPTION));
        //Client side data generators
        addProvider(gen, event.includeClient(), GeneratorsLangProvider::new);
        addProvider(gen, event.includeClient(), output -> new GeneratorsSoundProvider(output, existingFileHelper));
        addProvider(gen, event.includeClient(), output -> new GeneratorsSpriteSourceProvider(output, existingFileHelper));
        //Let the blockstate provider see models generated by the item model provider
        GeneratorsItemModelProvider itemModelProvider = new GeneratorsItemModelProvider(gen.getPackOutput(), existingFileHelper);
        gen.addProvider(event.includeClient(), itemModelProvider);
        addProvider(gen, event.includeClient(), output -> new GeneratorsBlockStateProvider(output, itemModelProvider.existingFileHelper));
        //Server side data generators
        addProvider(gen, event.includeServer(), output -> new GeneratorsTagProvider(output, lookupProvider, existingFileHelper));
        addProvider(gen, event.includeServer(), GeneratorsLootProvider::new);
        addProvider(gen, event.includeServer(), output -> new GeneratorsRecipeProvider(output, existingFileHelper));
        addProvider(gen, event.includeServer(), output -> new GeneratorsAdvancementProvider(output, existingFileHelper));
    }

    private static <PROVIDER extends DataProvider> void addProvider(DataGenerator gen, boolean run, DataProvider.Factory<PROVIDER> factory) {
        gen.addProvider(run, factory);
    }
}