package mekanism.api.recipes;

import mekanism.api.recipes.basic.BasicActivatingRecipe;
import mekanism.api.recipes.basic.BasicCentrifugingRecipe;
import mekanism.api.recipes.basic.BasicChemicalCrystallizerRecipe;
import mekanism.api.recipes.basic.BasicChemicalDissolutionRecipe;
import mekanism.api.recipes.basic.BasicChemicalInfuserRecipe;
import mekanism.api.recipes.basic.BasicChemicalOxidizerRecipe;
import mekanism.api.recipes.basic.BasicCombinerRecipe;
import mekanism.api.recipes.basic.BasicCompressingRecipe;
import mekanism.api.recipes.basic.BasicCrushingRecipe;
import mekanism.api.recipes.basic.BasicElectrolysisRecipe;
import mekanism.api.recipes.basic.BasicEnrichingRecipe;
import mekanism.api.recipes.basic.BasicFluidSlurryToSlurryRecipe;
import mekanism.api.recipes.basic.BasicFluidToFluidRecipe;
import mekanism.api.recipes.basic.BasicGasConversionRecipe;
import mekanism.api.recipes.basic.BasicInjectingRecipe;
import mekanism.api.recipes.basic.BasicItemStackToEnergyRecipe;
import mekanism.api.recipes.basic.BasicItemStackToInfuseTypeRecipe;
import mekanism.api.recipes.basic.BasicItemStackToPigmentRecipe;
import mekanism.api.recipes.basic.BasicMetallurgicInfuserRecipe;
import mekanism.api.recipes.basic.BasicNucleosynthesizingRecipe;
import mekanism.api.recipes.basic.BasicPaintingRecipe;
import mekanism.api.recipes.basic.BasicPigmentMixingRecipe;
import mekanism.api.recipes.basic.BasicPressurizedReactionRecipe;
import mekanism.api.recipes.basic.BasicPurifyingRecipe;
import mekanism.api.recipes.basic.BasicRotaryRecipe;
import mekanism.api.recipes.basic.BasicSawmillRecipe;
import mekanism.api.recipes.basic.BasicSmeltingRecipe;
import net.minecraft.world.item.crafting.RecipeSerializer;
import net.neoforged.neoforge.registries.RegistryObject;

public class MekanismRecipeSerializers {
    public static RegistryObject<RecipeSerializer<BasicCrushingRecipe>> CRUSHING;
    public static RegistryObject<RecipeSerializer<BasicEnrichingRecipe>> ENRICHING;
    public static RegistryObject<RecipeSerializer<BasicSmeltingRecipe>> SMELTING;
    public static RegistryObject<RecipeSerializer<BasicChemicalInfuserRecipe>> CHEMICAL_INFUSING;
    public static RegistryObject<RecipeSerializer<BasicCombinerRecipe>> COMBINING;
    public static RegistryObject<RecipeSerializer<BasicElectrolysisRecipe>> SEPARATING;
    public static RegistryObject<RecipeSerializer<BasicFluidSlurryToSlurryRecipe>> WASHING;
    public static RegistryObject<RecipeSerializer<BasicFluidToFluidRecipe>> EVAPORATING;
    public static RegistryObject<RecipeSerializer<BasicActivatingRecipe>> ACTIVATING;
    public static RegistryObject<RecipeSerializer<BasicCentrifugingRecipe>> CENTRIFUGING;
    public static RegistryObject<RecipeSerializer<BasicChemicalCrystallizerRecipe>> CRYSTALLIZING;
    public static RegistryObject<RecipeSerializer<BasicChemicalDissolutionRecipe>> DISSOLUTION;
    public static RegistryObject<RecipeSerializer<BasicCompressingRecipe>> COMPRESSING;
    public static RegistryObject<RecipeSerializer<BasicPurifyingRecipe>> PURIFYING;
    public static RegistryObject<RecipeSerializer<BasicInjectingRecipe>> INJECTING;
    public static RegistryObject<RecipeSerializer<BasicNucleosynthesizingRecipe>> NUCLEOSYNTHESIZING;
    public static RegistryObject<RecipeSerializer<BasicItemStackToEnergyRecipe>> ENERGY_CONVERSION;
    public static RegistryObject<RecipeSerializer<BasicGasConversionRecipe>> GAS_CONVERSION;
    public static RegistryObject<RecipeSerializer<BasicChemicalOxidizerRecipe>> OXIDIZING;
    public static RegistryObject<RecipeSerializer<BasicItemStackToInfuseTypeRecipe>> INFUSION_CONVERSION;
    public static RegistryObject<RecipeSerializer<BasicItemStackToPigmentRecipe>> PIGMENT_EXTRACTING;
    public static RegistryObject<RecipeSerializer<BasicPigmentMixingRecipe>> PIGMENT_MIXING;
    public static RegistryObject<RecipeSerializer<BasicMetallurgicInfuserRecipe>> METALLURGIC_INFUSING;
    public static RegistryObject<RecipeSerializer<BasicPaintingRecipe>> PAINTING;
    public static RegistryObject<RecipeSerializer<BasicPressurizedReactionRecipe>> REACTION;
    public static RegistryObject<RecipeSerializer<BasicRotaryRecipe>> ROTARY;
    public static RegistryObject<RecipeSerializer<BasicSawmillRecipe>> SAWING;
}
