name: General Issue
description: Report a bug or problem with Mekanism
body:
  - type: markdown
    attributes:
      value: "*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*"
  - type: textarea
    attributes:
      label: Issue description
      description: A clear and concise description of the issue and if appropriate what the expected outcome should have been.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: If there are specific steps that need to be taken to reproduce the issue list them here.
      placeholder: |
        1. Start by doing...
        2. Next do...
        3. See result described above
  - type: dropdown
    id: minecraft-version
    attributes:
      label: Minecraft version
      description: What version of Minecraft are you using?
      options:
        - 1.16.5 (Latest)
        - 1.15.x or earlier (No longer being developed)
    validations:
      required: true
  - type: input
    attributes:
      label: Forge version
      description: What version of Forge are you using?
      placeholder: e.g. 36.1.32
    validations:
      required: true
  - type: dropdown
    id: mekanism-version
    attributes:
      label: Mekanism version
      description: What version of Mekanism are you using?
      options:
        - Current Dev Branch (Manually Compiled)
        - 10.1.2 (Latest)
        - 10.1.1
        - 10.1.0
        - 10.0.24
        - 10.0.23
        - 10.0.22
        - 10.0.21
        - Older
    validations:
      required: true
  - type: textarea
    attributes:
      label: Other relevant versions
      description: If this issue is related to any other mods list their versions here.
  - type: input
    attributes:
      label: "If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)"
      description: "Please provide a [gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. (Make sure that it isn't set to expire!)"