package mekanism.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;

@SideOnly(Side.CLIENT)
public class ModelRotaryCondensentrator extends ModelBase
{
	ModelRenderer GasBottleLid1;
	ModelRenderer GasBottleLid2;
	ModelRenderer GasBottleDecor1;
	ModelRenderer GasBottleDecor2;
	ModelRenderer GasBottleDecor3;
	ModelRenderer GasBottleDecor4;
	ModelRenderer GasBottle1;
	ModelRenderer GasBottle2;
	ModelRenderer GasBottleBot1;
	ModelRenderer GasBottleBot2;
	ModelRenderer LiqBottleLid1;
	ModelRenderer LiqBottleLid2;
	ModelRenderer LiqBottleBot1;
	ModelRenderer LiqBottleBot2;
	ModelRenderer LiqBottle2;
	ModelRenderer LiqBottle1;
	ModelRenderer LiqBottleDecor1;
	ModelRenderer LiqBottleDecor2;
	ModelRenderer LiqBottleDecor3;
	ModelRenderer LiqBottleDecor4;
	ModelRenderer GasInput;
	ModelRenderer MidSection1;
	ModelRenderer MidSection2;
	ModelRenderer LiquidOutput;
	ModelRenderer MidSection3;

	public ModelRotaryCondensentrator()
	{
		textureWidth = 128;
		textureHeight = 128;

		GasBottleLid1 = new ModelRenderer(this, 0, 40);
		GasBottleLid1.addBox(0F, 0F, 0F, 6, 1, 6);
		GasBottleLid1.setRotationPoint(-7F, 11F, 1F);
		GasBottleLid1.setTextureSize(128, 128);
		GasBottleLid1.mirror = true;
		setRotation(GasBottleLid1, 0F, 0F, 0F);
		GasBottleLid2 = new ModelRenderer(this, 0, 40);
		GasBottleLid2.addBox(0F, 0F, 0F, 6, 1, 6);
		GasBottleLid2.setRotationPoint(1F, 11F, 1F);
		GasBottleLid2.setTextureSize(128, 128);
		GasBottleLid2.mirror = true;
		setRotation(GasBottleLid2, 0F, 0F, 0F);
		GasBottleDecor1 = new ModelRenderer(this, 0, 33);
		GasBottleDecor1.addBox(0F, 0F, 0F, 5, 1, 5);
		GasBottleDecor1.setRotationPoint(1.5F, 21F, 1.5F);
		GasBottleDecor1.setTextureSize(128, 128);
		GasBottleDecor1.mirror = true;
		setRotation(GasBottleDecor1, 0F, 0F, 0F);
		GasBottleDecor2 = new ModelRenderer(this, 0, 33);
		GasBottleDecor2.addBox(0F, 0F, 0F, 5, 1, 5);
		GasBottleDecor2.setRotationPoint(1.5F, 13F, 1.5F);
		GasBottleDecor2.setTextureSize(128, 128);
		GasBottleDecor2.mirror = true;
		setRotation(GasBottleDecor2, 0F, 0F, 0F);
		GasBottleDecor3 = new ModelRenderer(this, 0, 33);
		GasBottleDecor3.addBox(0F, 0F, 0F, 5, 1, 5);
		GasBottleDecor3.setRotationPoint(-6.5F, 21F, 1.5F);
		GasBottleDecor3.setTextureSize(128, 128);
		GasBottleDecor3.mirror = true;
		setRotation(GasBottleDecor3, 0F, 0F, 0F);
		GasBottleDecor4 = new ModelRenderer(this, 0, 33);
		GasBottleDecor4.addBox(0F, 0F, 0F, 5, 1, 5);
		GasBottleDecor4.setRotationPoint(-6.5F, 13F, 1.5F);
		GasBottleDecor4.setTextureSize(128, 128);
		GasBottleDecor4.mirror = true;
		setRotation(GasBottleDecor4, 0F, 0F, 0F);
		GasBottle1 = new ModelRenderer(this, 0, 48);
		GasBottle1.addBox(0F, 0F, 0F, 4, 11, 4);
		GasBottle1.setRotationPoint(-6F, 12F, 2F);
		GasBottle1.setTextureSize(128, 128);
		GasBottle1.mirror = true;
		setRotation(GasBottle1, 0F, 0F, 0F);
		GasBottle2 = new ModelRenderer(this, 0, 48);
		GasBottle2.addBox(0F, 0F, 0F, 4, 11, 4);
		GasBottle2.setRotationPoint(2F, 12F, 2F);
		GasBottle2.setTextureSize(128, 128);
		GasBottle2.mirror = true;
		setRotation(GasBottle2, 0F, 0F, 0F);
		GasBottleBot1 = new ModelRenderer(this, 0, 40);
		GasBottleBot1.addBox(0F, 0F, 0F, 6, 1, 6);
		GasBottleBot1.setRotationPoint(-7F, 23F, 1F);
		GasBottleBot1.setTextureSize(128, 128);
		GasBottleBot1.mirror = true;
		setRotation(GasBottleBot1, 0F, 0F, 0F);
		GasBottleBot2 = new ModelRenderer(this, 0, 40);
		GasBottleBot2.addBox(0F, 0F, 0F, 6, 1, 6);
		GasBottleBot2.setRotationPoint(1F, 23F, 1F);
		GasBottleBot2.setTextureSize(128, 128);
		GasBottleBot2.mirror = true;
		setRotation(GasBottleBot2, 0F, 0F, 0F);
		LiqBottleLid1 = new ModelRenderer(this, 25, 40);
		LiqBottleLid1.addBox(0F, 0F, 0F, 6, 1, 6);
		LiqBottleLid1.setRotationPoint(-7F, 11F, -7F);
		LiqBottleLid1.setTextureSize(128, 128);
		LiqBottleLid1.mirror = true;
		setRotation(LiqBottleLid1, 0F, 0F, 0F);
		LiqBottleLid2 = new ModelRenderer(this, 25, 40);
		LiqBottleLid2.addBox(0F, 0F, 0F, 6, 1, 6);
		LiqBottleLid2.setRotationPoint(1F, 11F, -7F);
		LiqBottleLid2.setTextureSize(128, 128);
		LiqBottleLid2.mirror = true;
		setRotation(LiqBottleLid2, 0F, 0F, 0F);
		LiqBottleBot1 = new ModelRenderer(this, 25, 40);
		LiqBottleBot1.addBox(0F, 0F, 0F, 6, 1, 6);
		LiqBottleBot1.setRotationPoint(-7F, 23F, -7F);
		LiqBottleBot1.setTextureSize(128, 128);
		LiqBottleBot1.mirror = true;
		setRotation(LiqBottleBot1, 0F, 0F, 0F);
		LiqBottleBot2 = new ModelRenderer(this, 25, 40);
		LiqBottleBot2.addBox(0F, 0F, 0F, 6, 1, 6);
		LiqBottleBot2.setRotationPoint(1F, 23F, -7F);
		LiqBottleBot2.setTextureSize(128, 128);
		LiqBottleBot2.mirror = true;
		setRotation(LiqBottleBot2, 0F, 0F, 0F);
		LiqBottle2 = new ModelRenderer(this, 25, 48);
		LiqBottle2.addBox(0F, 0F, 0F, 4, 11, 4);
		LiqBottle2.setRotationPoint(2F, 12F, -6F);
		LiqBottle2.setTextureSize(128, 128);
		LiqBottle2.mirror = true;
		setRotation(LiqBottle2, 0F, 0F, 0F);
		LiqBottle1 = new ModelRenderer(this, 25, 48);
		LiqBottle1.addBox(0F, 0F, 0F, 4, 11, 4);
		LiqBottle1.setRotationPoint(-6F, 12F, -6F);
		LiqBottle1.setTextureSize(128, 128);
		LiqBottle1.mirror = true;
		setRotation(LiqBottle1, 0F, 0F, 0F);
		LiqBottleDecor1 = new ModelRenderer(this, 25, 33);
		LiqBottleDecor1.addBox(0F, 0F, 0F, 5, 1, 5);
		LiqBottleDecor1.setRotationPoint(1.5F, 21F, -6.5F);
		LiqBottleDecor1.setTextureSize(128, 128);
		LiqBottleDecor1.mirror = true;
		setRotation(LiqBottleDecor1, 0F, 0F, 0F);
		LiqBottleDecor2 = new ModelRenderer(this, 25, 33);
		LiqBottleDecor2.addBox(0F, 0F, 0F, 5, 1, 5);
		LiqBottleDecor2.setRotationPoint(1.5F, 13F, -6.5F);
		LiqBottleDecor2.setTextureSize(128, 128);
		LiqBottleDecor2.mirror = true;
		setRotation(LiqBottleDecor2, 0F, 0F, 0F);
		LiqBottleDecor3 = new ModelRenderer(this, 25, 33);
		LiqBottleDecor3.addBox(0F, 0F, 0F, 5, 1, 5);
		LiqBottleDecor3.setRotationPoint(-6.5F, 21F, -6.5F);
		LiqBottleDecor3.setTextureSize(128, 128);
		LiqBottleDecor3.mirror = true;
		setRotation(LiqBottleDecor3, 0F, 0F, 0F);
		LiqBottleDecor4 = new ModelRenderer(this, 25, 33);
		LiqBottleDecor4.addBox(0F, 0F, 0F, 5, 1, 5);
		LiqBottleDecor4.setRotationPoint(-6.5F, 13F, -6.5F);
		LiqBottleDecor4.setTextureSize(128, 128);
		LiqBottleDecor4.mirror = true;
		setRotation(LiqBottleDecor4, 0F, 0F, 0F);
		GasInput = new ModelRenderer(this, 0, 24);
		GasInput.addBox(0F, 0F, 0F, 6, 6, 1);
		GasInput.setRotationPoint(-3F, 13F, 7F);
		GasInput.setTextureSize(128, 128);
		GasInput.mirror = true;
		setRotation(GasInput, 0F, 0F, 0F);
		MidSection1 = new ModelRenderer(this, 15, 20);
		MidSection1.addBox(0F, 0F, 0F, 4, 5, 6);
		MidSection1.setRotationPoint(-2F, 18F, 1F);
		MidSection1.setTextureSize(128, 128);
		MidSection1.mirror = true;
		setRotation(MidSection1, 0F, 0F, 0F);
		MidSection2 = new ModelRenderer(this, 37, 0);
		MidSection2.addBox(0F, 0F, 0F, 6, 7, 8);
		MidSection2.setRotationPoint(-3F, 17F, -7F);
		MidSection2.setTextureSize(128, 128);
		MidSection2.mirror = true;
		setRotation(MidSection2, 0F, 0F, 0F);
		LiquidOutput = new ModelRenderer(this, 36, 22);
		LiquidOutput.addBox(0F, 0F, 0F, 8, 8, 1);
		LiquidOutput.setRotationPoint(-4F, 12F, -8F);
		LiquidOutput.setTextureSize(128, 128);
		LiquidOutput.mirror = true;
		setRotation(LiquidOutput, 0F, 0F, 0F);
		MidSection3 = new ModelRenderer(this, 0, 0);
		MidSection3.addBox(0F, 0F, 0F, 4, 2, 14);
		MidSection3.setRotationPoint(-2F, 15F, -7F);
		MidSection3.setTextureSize(128, 128);
		MidSection3.mirror = true;
		setRotation(MidSection3, 0F, 0F, 0F);
	}

	public void render(float size)
	{
		GasBottleLid1.render(size);
		GasBottleLid2.render(size);
		GasBottleDecor1.render(size);
		GasBottleDecor2.render(size);
		GasBottleDecor3.render(size);
		GasBottleDecor4.render(size);
		GasBottle1.render(size);
		GasBottle2.render(size);
		GasBottleBot1.render(size);
		GasBottleBot2.render(size);
		LiqBottleLid1.render(size);
		LiqBottleLid2.render(size);
		LiqBottleBot1.render(size);
		LiqBottleBot2.render(size);
		LiqBottle2.render(size);
		LiqBottle1.render(size);
		LiqBottleDecor1.render(size);
		LiqBottleDecor2.render(size);
		LiqBottleDecor3.render(size);
		LiqBottleDecor4.render(size);
		GasInput.render(size);
		MidSection1.render(size);
		MidSection2.render(size);
		LiquidOutput.render(size);
		MidSection3.render(size);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z)
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}
}
