plugins {
    id 'java'
}

group = 'mekanism.annotation-processor'
version = '2.0.0'
java.toolchain.languageVersion = JavaLanguageVersion.of("${java_version}")

repositories {
    def repo = maven {
        name = 'ZenCode'
        url = 'https://maven.blamejared.com'
    }
    exclusiveContent {
        forRepositories(repo)
        filter {
            includeGroup('org.openzen.zencode')
        }
    }
    maven {
        name = 'MojangMeta'
        url = 'https://maven.neoforged.net/mojang-meta'
        content {
            includeModule('net.neoforged', 'minecraft-dependencies')
        }
    }
    mavenCentral()
}

dependencies {
    //Query the version of GSON and JSpecify used by the version of MC that we are developing for to ensure no extra files have to be downloaded
    implementation(platform("net.neoforged:minecraft-dependencies:${project.minecraft_version}"))
    implementation('org.jspecify:jspecify')
    implementation('com.google.code.gson:gson')

    implementation('org.openzen.zencode:JavaAnnotations:0.3.8')
    implementation('com.palantir.javapoet:javapoet:0.14.0')
}
