package mekanism.additions.common;

import mekanism.additions.client.AdditionsBlockStateProvider;
import mekanism.additions.client.AdditionsItemModelProvider;
import mekanism.additions.client.AdditionsLangProvider;
import mekanism.additions.client.AdditionsSoundProvider;
import mekanism.additions.common.loot.AdditionsLootProvider;
import mekanism.additions.common.recipe.AdditionsRecipeProvider;
import mekanism.additions.common.world_modifier.AdditionsBiomeModifierProvider;
import mekanism.additions.common.world_modifier.AdditionsStructureModifierProvider;
import mekanism.common.MekanismDataGenerator;
import net.minecraft.data.DataGenerator;
import net.minecraftforge.common.data.ExistingFileHelper;
import net.minecraftforge.data.event.GatherDataEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod.EventBusSubscriber;
import net.minecraftforge.fml.common.Mod.EventBusSubscriber.Bus;

@EventBusSubscriber(modid = MekanismAdditions.MODID, bus = Bus.MOD)
public class AdditionsDataGenerator {

    private AdditionsDataGenerator() {
    }

    @SubscribeEvent
    public static void gatherData(GatherDataEvent event) {
        MekanismDataGenerator.bootstrapConfigs(MekanismAdditions.MODID);
        DataGenerator gen = event.getGenerator();
        ExistingFileHelper existingFileHelper = event.getExistingFileHelper();
        //Client side data generators
        gen.addProvider(event.includeClient(), new AdditionsLangProvider(gen));
        gen.addProvider(event.includeClient(), new AdditionsSoundProvider(gen, existingFileHelper));
        //Let the blockstate provider see models generated by the item model provider
        AdditionsItemModelProvider itemModelProvider = new AdditionsItemModelProvider(gen, existingFileHelper);
        gen.addProvider(event.includeClient(), itemModelProvider);
        gen.addProvider(event.includeClient(), new AdditionsBlockStateProvider(gen, itemModelProvider.existingFileHelper));
        //Server side data generators
        gen.addProvider(event.includeServer(), new AdditionsTagProvider(gen, existingFileHelper));
        gen.addProvider(event.includeServer(), new AdditionsLootProvider(gen));
        gen.addProvider(event.includeServer(), new AdditionsBiomeModifierProvider(gen));
        gen.addProvider(event.includeServer(), new AdditionsStructureModifierProvider(gen));
        gen.addProvider(event.includeServer(), new AdditionsRecipeProvider(gen, existingFileHelper));
        gen.addProvider(event.includeServer(), new AdditionsAdvancementProvider(gen, existingFileHelper));
    }
}