package mekanism.additions.common;

import java.util.concurrent.CompletableFuture;
import mekanism.additions.client.AdditionsBlockStateProvider;
import mekanism.additions.client.AdditionsItemModelProvider;
import mekanism.additions.client.AdditionsLangProvider;
import mekanism.additions.client.AdditionsSoundProvider;
import mekanism.additions.client.AdditionsSpriteSourceProvider;
import mekanism.additions.common.loot.AdditionsLootProvider;
import mekanism.additions.common.recipe.AdditionsRecipeProvider;
import mekanism.common.BasePackMetadataGenerator;
import mekanism.common.MekanismDataGenerator;
import net.minecraft.core.HolderLookup;
import net.minecraft.data.DataGenerator;
import net.minecraft.data.DataProvider;
import net.minecraftforge.common.data.ExistingFileHelper;
import net.minecraftforge.data.event.GatherDataEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod.EventBusSubscriber;
import net.minecraftforge.fml.common.Mod.EventBusSubscriber.Bus;

@EventBusSubscriber(modid = MekanismAdditions.MODID, bus = Bus.MOD)
public class AdditionsDataGenerator {

    private AdditionsDataGenerator() {
    }

    @SubscribeEvent
    public static void gatherData(GatherDataEvent event) {
        MekanismDataGenerator.bootstrapConfigs(MekanismAdditions.MODID);
        DataGenerator gen = event.getGenerator();
        ExistingFileHelper existingFileHelper = event.getExistingFileHelper();
        CompletableFuture<HolderLookup.Provider> lookupProvider = event.getLookupProvider();
        addProvider(gen, true, output -> new BasePackMetadataGenerator(output, AdditionsLang.PACK_DESCRIPTION));
        //Client side data generators
        addProvider(gen, event.includeClient(), AdditionsLangProvider::new);
        addProvider(gen, event.includeClient(), output -> new AdditionsSoundProvider(output, existingFileHelper));
        addProvider(gen, event.includeClient(), output -> new AdditionsSpriteSourceProvider(output, existingFileHelper));
        //Let the blockstate provider see models generated by the item model provider
        AdditionsItemModelProvider itemModelProvider = new AdditionsItemModelProvider(gen.getPackOutput(), existingFileHelper);
        gen.addProvider(event.includeClient(), itemModelProvider);
        addProvider(gen, event.includeClient(), output -> new AdditionsBlockStateProvider(output, itemModelProvider.existingFileHelper));
        //Server side data generators
        addProvider(gen, event.includeServer(), output -> new AdditionsTagProvider(output, lookupProvider, existingFileHelper));
        addProvider(gen, event.includeServer(), AdditionsLootProvider::new);
        addProvider(gen, event.includeServer(), output -> new AdditionsDatapackRegistryProvider(output, lookupProvider));
        addProvider(gen, event.includeServer(), output -> new AdditionsRecipeProvider(output, existingFileHelper));
        addProvider(gen, event.includeServer(), output -> new AdditionsAdvancementProvider(output, existingFileHelper));
    }

    private static <PROVIDER extends DataProvider> void addProvider(DataGenerator gen, boolean run, DataProvider.Factory<PROVIDER> factory) {
        gen.addProvider(run, factory);
    }
}