name: "Run Game Tests"

on:
  #push: TODO - 26.1: re-enable when compiles
  #  branches: [ "26.1" ]
  pull_request:
    branches: [ "26.1" ]
    types:
      - synchronize
      - opened
      - ready_for_review
      - reopened
    paths:
      - '**.java'

jobs:
  test:
    name: Game Tests
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-provider: basic
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Run Game Tests with Gradle
        run: sh gradlew runGameTestServer

      - name: Run Unit Tests with Gradle
        run: sh gradlew test